config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'url#index'
  get '/stats', to: 'url#stats'
  get '/:shorten', to: 'url#redirector'
  post 'generate_shorten_url', to: 'url#create'
end

app/models/analytic.rb
# frozen_string_literal: true

class Analytic < ApplicationRecord
  belongs_to :url
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
# frozen_string_literal: true

class Url < ApplicationRecord #:nodoc:
  has_one :analytic

  before_save :validates
  before_create :assign_shorten

  def validates
    raise 'Invalid URL' unless source.include?('.')

    self.source = enhance_url
  end

  def assign_shorten
    self.shorten = SecureRandom.alphanumeric(5)
  end

  def generate_shorten
    [ENDPOINTS.domain, shorten].join('/')
  end

  def enhance_url(protocol: nil)
    return source unless source.present?

    protocol ||= 'https'
    if source[%r{\Ahttp:\/\/}] || source[%r{\Ahttps:\/\/}]
      source
    else
      [protocol, source].join('://')
    end
  end

  # Should be accessed in Background process
  def update_analytic(country, ip)
    analytic = self.analytic || Analytic.new(url_id: id)
    analytic.total_request += 1
    detail = analytic.detail
    detail[country] ||= { 'no_of_hits' => 0, 'ip_addresses' => [] }
    country_details = detail[country]
    country_details['no_of_hits'] += 1
    country_details['ip_addresses'] = country_details['ip_addresses']
                                      .push(ip).compact.uniq
    analytic.save!
  end

  def self.stats
    cols = ['urls.source as source', 'urls.shorten as shorten',
            'analytics.detail as detail', 'analytics.total_request as total_hits']
    mapping = cols.join(', ')
    joins(:analytic).select(mapping)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/url_controller.rb
# frozen_string_literal: true

class UrlController < ApplicationController #:nodoc:
  def index; end

  def create
    @url = Url.create!(url_params)
  end

  def redirector
    url = Url.find_by(shorten: params[:shorten])
    raise 'Invalid URL' unless url

    redirect_to url.source
    url.update_analytic(request.location.country, request.ip)
  end

  def stats
    @statistics = Url.stats
  end

  private

  def url_params
    params.require(:url).permit(:source)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def top_countries(details)
    sort = details.sort_by { |_country, detail| detail['no_of_hits'] }
    Hash[sort.reverse.first(3)].keys.join(', ')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortner</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/url/create.js.erb
var displayList = document.getElementById("url-listing");
displayList.classList.remove("hide");
var node = document.createElement("p")
var textnode = document.createTextNode("<%= @url.generate_shorten %>");
node.appendChild(textnode);
document.getElementById("url-listing").appendChild(node);

app/views/url/index.html.erb
<%= form_with(url: generate_shorten_url_path, method: "post", id: "create_shorten") do |f| %>
  <%= content_tag(:h1, 'Welcome to short.com') %>
  <%= content_tag(:h4, 'Please enter your URL here') %>
  <%= f.text_field "url[source]"%>
  <%= f.submit "Generate" %>
<% end %>

<div id="url-listing" class="hide">
<h5> Here's your short URL! </h5>
</div>

app/views/url/stats.html.erb
<%= content_tag(:h1, 'Analytics') %>
<% @statistics.each do |object| %>
  <%= content_tag(:h3, object.source) %>
  <%= content_tag(:h4, "#{ENDPOINTS.domain}/#{object.shorten}") %>
  <%= content_tag(:p, "Total Clicks: #{object.total_hits}") %>
  <%= content_tag(:p, "Top Countries: #{top_countries(object.detail)}") %>
  <%= content_tag(:hr) %>
<% end %>